version: '2.3'
services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: traefik
    command: |
      --log.level=DEBUG
      --providers.docker=true
      --providers.docker.watch=true
      --providers.docker.exposedbydefault=false
      --entrypoints.http.address=:80
      --entrypoints.https.address=:443
      --api.dashboard=true
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: "Host(`traefik.${LUPUS_LOCALDEV_BASE_DOMAIN:-localdev.space}`)"
      traefik.http.routers.traefik.entrypoints: "http"

    ports:
      - "${LUPUS_LOCALDEV_WEB_LISTEN_IP:-127.0.0.1}:${LUPUS_LOCALDEV_WEB_HTTP_PORT:-80}:80"
      - "${LUPUS_LOCALDEV_WEB_LISTEN_IP:-127.0.0.1}:${LUPUS_LOCALDEV_WEB_HTTPS_PORT:-443}:443"
    expose:
      # traefik Dashboard port
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/etc/traefik/acme
    networks:
      - default
      - traefik
    restart: ${LUPUS_LOCALDEV_CONTAINER_RESTART:-always}

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: ${LUPUS_LOCALDEV_CONTAINER_RESTART:-always}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      traefik.enable: true
      traefik.http.services.portainer_service.loadbalancer.server.port: 9000
      traefik.http.routers.portainer.entrypoints: "http"
      traefik.http.routers.portainer.rule: "Host(`portainer.${LUPUS_LOCALDEV_BASE_DOMAIN:-localdev.space}`)"

networks:
  traefik:
    name: traefik

volumes:
  portainer_data:
